language: java

env:
 - DISPLAY=:99.0

before_script:
 - cd jts
 - "sh -e /etc/init.d/xvfb start"
 
script: mvn install

after_script:
 - cd ../jts-test-library
 - mvn exec:exec

notifications:
  email: false

jdk:
 - openjdk6
 - openjdk7
 - oraclejdk7

